import { useState } from "react"
import { WeeklyCalendar } from "../components/plans/WeeklyCalendar"
import { useAppStore, type MealEntry } from "../store/useAppStore"
import { format } from "date-fns"
import { Plus, Sparkles, Loader2, ShoppingCart, X, Check, ChefHat, Trash2 } from "lucide-react"
import { cn } from "../lib/utils"
import { AddFoodForm } from "../components/log/AddFoodForm"
import { ExerciseModal } from "../components/workout/ExerciseModal"
import { generateMealPlan, getApiKey } from "../lib/ai"
import { toast } from "sonner"

export default function Plans() {
    const [selectedDate, setSelectedDate] = useState(format(new Date(), 'yyyy-MM-dd'))
    const [activeTab, setActiveTab] = useState<MealEntry['mealType']>('breakfast')
    const [isAddingMode, setIsAddingMode] = useState(false)
    const [editingMeal, setEditingMeal] = useState<MealEntry | null>(null)
    const [isGenerating, setIsGenerating] = useState(false)
    const [showShoppingList, setShowShoppingList] = useState(false)
    const [showIngredientsInput, setShowIngredientsInput] = useState(false)
    const [availableIngredients, setAvailableIngredients] = useState('')

    const [checkedItems, setCheckedItems] = useState<string[]>([])

    const [showExerciseModal, setShowExerciseModal] = useState(false)

    const plans = useAppStore(state => state.plans[selectedDate])
    const logs = useAppStore(state => state.logs[selectedDate])
    const user = useAppStore(state => state.user)
    const isDesktopView = useAppStore(state => state.isDesktopView)
    const addPlanEntry = useAppStore(state => state.addPlanEntry)
    const updatePlanEntry = useAppStore(state => state.updatePlanEntry)
    const removePlanEntry = useAppStore(state => state.removePlanEntry)
    const exerciseLog = useAppStore(state => state.exerciseLogs?.[selectedDate])
    const addExerciseEntry = useAppStore(state => state.addExerciseEntry)
    const removeExerciseEntry = useAppStore(state => state.removeExerciseEntry)

    const entries = plans?.entries.filter(e => e.mealType === activeTab) || []

    const allIngredients = (plans?.entries || []).reduce((acc, entry) => {
        if (entry && Array.isArray(entry.ingredients)) {
            entry.ingredients.forEach(ing => {
                if (ing && !acc.includes(ing)) acc.push(ing)
            })
        }
        return acc
    }, [] as string[])

    // Final Calculations
    const plannedCalories = (plans?.entries || []).reduce((acc, e) => acc + e.calories, 0)
    const actualCalories = (logs?.entries || []).reduce((acc, e) => acc + e.calories, 0)

    const totalExerciseMinutes = (exerciseLog?.entries || []).reduce((acc, e) => acc + e.durationMinutes, 0)

    const toggleItem = (item: string) => {
        setCheckedItems(prev =>
            prev.includes(item) ? prev.filter(i => i !== item) : [...prev, item]
        )
    }

    const handleGenerateAI = async () => {
        const apiKey = getApiKey()

        if (!apiKey) {
            toast.error("AI Features Restricted", {
                description: "Please configure your Gemini API Key in the Profile section to enable Smart Planning."
            })
            return
        }
        setIsGenerating(true)
        try {
            const suggestedMeals = await generateMealPlan(user, showIngredientsInput ? availableIngredients : undefined)
            // Add all suggested meals to the plan
            for (const meal of suggestedMeals) {
                await addPlanEntry(selectedDate, meal)
            }
            toast.success(showIngredientsInput ? "Menu Custom-Made!" : "Meal Plan Generated!", {
                description: showIngredientsInput
                    ? `AI used your ${availableIngredients.split(',').length} ingredients.`
                    : "AI has created a balanced menu for your day."
            })
            if (showIngredientsInput) setShowIngredientsInput(false)
        } catch (e: any) {
            console.error("Meal planning failed:", e)
            toast.error("Generation Failed", {
                description: e.message || "Please check your API key and connection."
            })
        } finally {
            setIsGenerating(false)
        }
    }

    const handleShareWhatsApp = () => {
        const dateStr = format(new Date(selectedDate), 'EEEE, MMM do')
        const items = allIngredients.map(ing => `- ${checkedItems.includes(ing) ? '[DONE] ' : ''}${ing}`).join('\n')
        const message = `🛒 Shopping List for ${dateStr}\n\n${items}\n\nGenerated by Health Companion AI`
        window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank')
    }

    return (
        <div className="page-container space-y-6">
            {/* Background Blob */}
            <div className="absolute -top-20 -right-20 w-80 h-80 bg-indigo-500/5 dark:bg-indigo-400/5 rounded-full blur-3xl -z-10 animate-blob"></div>
            <div className="absolute top-1/2 -left-20 w-80 h-80 bg-purple-500/5 dark:bg-purple-400/5 rounded-full blur-3xl -z-10 animate-blob animation-delay-2000"></div>

            <header className="space-y-4 px-1">
                <div className="flex justify-between items-center">
                    <div className="space-y-1">
                        <h1 className="text-2xl font-black bg-gradient-to-r from-slate-900 to-slate-700 dark:from-white dark:to-slate-300 bg-clip-text text-transparent tracking-tight">
                            Meal Planner
                        </h1>
                        <p className="text-[10px] text-slate-400 dark:text-slate-500 font-bold uppercase tracking-widest">
                            Design your perfect day
                        </p>
                    </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                    <button
                        onClick={handleGenerateAI}
                        disabled={isGenerating}
                        className={cn(
                            "col-span-2 glass dark:bg-indigo-500/10 dark:border-indigo-500/20 text-indigo-600 dark:text-indigo-400 p-4 rounded-3xl text-sm font-black flex items-center justify-center gap-3 hover:scale-[1.02] active:scale-[0.98] transition-all shadow-xl shadow-indigo-500/5",
                            showIngredientsInput && "hidden"
                        )}
                    >
                        {isGenerating ? <Loader2 size={20} className="animate-spin text-indigo-500" /> : <Sparkles size={20} className="text-indigo-500" />}
                        {isGenerating ? "AI Planning..." : "Smart AI Plan"}
                    </button>

                    <button
                        onClick={() => setShowIngredientsInput(!showIngredientsInput)}
                        className={cn(
                            "glass p-4 rounded-3xl text-[11px] font-black flex items-center justify-center gap-2 transition-all border-2",
                            showIngredientsInput
                                ? "bg-white border-slate-200 text-slate-900 shadow-xl shadow-white/10 col-span-2"
                                : "text-slate-600 dark:text-slate-300 border-transparent hover:border-slate-200 dark:hover:border-slate-800",
                            !showIngredientsInput && "flex-1"
                        )}
                    >
                        {showIngredientsInput ? (
                            <>
                                <X size={18} className="text-slate-900" />
                                <span className="uppercase tracking-widest">Close Fridge Mode</span>
                            </>
                        ) : (
                            <>
                                <ChefHat size={18} className="text-orange-500" />
                                <span className="uppercase tracking-widest">Fridge Mode</span>
                            </>
                        )}
                    </button>

                    {!showIngredientsInput && (
                        <button
                            onClick={() => {
                                setShowShoppingList(true)
                                setCheckedItems([]) // Reset list when opening
                            }}
                            className="glass p-4 rounded-3xl text-indigo-500 hover:text-indigo-600 dark:hover:text-indigo-400 transition-all hover:scale-[1.05] active:scale-[0.95] relative flex flex-col items-center justify-center gap-2 border-2 border-transparent hover:border-indigo-100 dark:hover:border-indigo-900/30"
                            title="Shopping List"
                        >
                            <ShoppingCart size={18} className="text-indigo-500" />
                            <span className="text-[11px] font-black uppercase tracking-widest text-slate-600 dark:text-slate-300">Grocery List</span>
                            {allIngredients.length > 0 && (
                                <span className="absolute top-3 right-8 bg-orange-500 text-white text-[9px] font-black w-5 h-5 rounded-full flex items-center justify-center border-2 border-white dark:border-slate-900 animate-in zoom-in shadow-lg shadow-orange-500/30">
                                    {allIngredients.length}
                                </span>
                            )}
                        </button>
                    )}

                    {showIngredientsInput && (
                        <div className="col-span-2 glass p-5 rounded-[2rem] space-y-4 animate-in slide-in-from-top-4 duration-300">
                            <div className="flex items-center gap-2 px-1">
                                <div className="w-1 h-3 bg-orange-500 rounded-full"></div>
                                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">What's in your Fridge?</label>
                            </div>
                            <textarea
                                placeholder="Eggs, spinach, chicken breast, rice..."
                                className="w-full p-4 bg-white/50 dark:bg-slate-950/50 border border-slate-100 dark:border-slate-800 rounded-2xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 transition-all font-bold text-xs min-h-[100px] resize-none"
                                value={availableIngredients}
                                onChange={(e) => setAvailableIngredients(e.target.value)}
                            />
                            <button
                                onClick={handleGenerateAI}
                                disabled={isGenerating || !availableIngredients.trim()}
                                className="w-full bg-slate-900 dark:bg-orange-500 text-white p-4 rounded-2xl text-xs font-black uppercase tracking-widest shadow-xl shadow-orange-500/20 active:scale-[0.98] transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                {isGenerating ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
                                {isGenerating ? "AI Cooking..." : "Get Suggestions"}
                            </button>
                        </div>
                    )}
                </div>
            </header>

            <WeeklyCalendar selectedDate={selectedDate} onSelect={setSelectedDate} />

            {/* Shopping List Modal */}
            {showShoppingList && (
                <div className={cn(
                    "fixed inset-0 bg-slate-950/60 backdrop-blur-sm z-[60] flex items-center justify-center p-4 animate-in fade-in duration-200 transition-all",
                    !isDesktopView && "left-1/2 -translate-x-1/2 w-full max-w-[430px]"
                )}>
                    <div className="w-full max-w-md glass-dark rounded-[2.5rem] overflow-hidden shadow-2xl">
                        <div className="p-8 space-y-6">
                            <div className="flex justify-between items-center">
                                <div className="space-y-1">
                                    <h3 className="text-2xl font-black text-white tracking-tight">Shopping List</h3>
                                    <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">{format(new Date(selectedDate), 'EEEE, MMM do')}</p>
                                </div>
                                <div className="flex items-center gap-4">
                                    <button
                                        onClick={handleShareWhatsApp}
                                        className="text-emerald-500 hover:scale-110 active:scale-90 transition-all"
                                        title="Share to WhatsApp"
                                    >
                                        <ShoppingCart size={20} />
                                    </button>
                                    <button onClick={() => setShowShoppingList(false)} className="text-slate-500 hover:text-white transition-colors">
                                        <X size={24} />
                                    </button>
                                </div>
                            </div>

                            <div className="space-y-4 max-h-[350px] overflow-y-auto pr-2 custom-scrollbar">
                                {allIngredients.length === 0 ? (
                                    <div className="text-center py-12 px-6 space-y-4">
                                        <div className="bg-slate-900/50 w-16 h-16 rounded-3xl flex items-center justify-center mx-auto mb-4 border border-white/5">
                                            <ShoppingCart size={32} className="text-slate-600" />
                                        </div>
                                        <div className="space-y-2">
                                            <p className="text-base font-black text-white">List is Empty</p>
                                            <p className="text-xs text-slate-500 font-medium leading-relaxed">
                                                {plans?.entries.length ? "Your planned meals don't have ingredients listed. Click on a meal to add them manually." : "No meals planned for this day yet. Generate a plan to see ingredients!"}
                                            </p>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="grid grid-cols-1 gap-2">
                                        {allIngredients.map((ing, i) => (
                                            <div
                                                key={i}
                                                onClick={() => toggleItem(ing)}
                                                className={cn(
                                                    "flex items-center gap-3 p-4 rounded-2xl border transition-all cursor-pointer group",
                                                    checkedItems.includes(ing)
                                                        ? "bg-indigo-500/10 border-indigo-500/20 opacity-60"
                                                        : "bg-white/5 border-white/5 hover:bg-white/10"
                                                )}
                                            >
                                                <div className={cn(
                                                    "w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all",
                                                    checkedItems.includes(ing)
                                                        ? "bg-indigo-500 border-indigo-500"
                                                        : "border-slate-700 group-hover:border-indigo-500/50"
                                                )}>
                                                    {checkedItems.includes(ing) && <Check size={14} className="text-white" />}
                                                </div>
                                                <span className={cn(
                                                    "text-sm font-medium transition-all",
                                                    checkedItems.includes(ing) ? "text-slate-400 line-through" : "text-slate-200"
                                                )}>
                                                    {ing}
                                                </span>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>

                            <div className="flex gap-3 pt-2">
                                <button
                                    onClick={() => setShowShoppingList(false)}
                                    className="flex-1 py-4 bg-slate-800 hover:bg-slate-700 text-white rounded-2xl font-black text-xs uppercase tracking-widest transition-all active:scale-[0.98]"
                                >
                                    Dismiss
                                </button>
                                <button
                                    onClick={handleShareWhatsApp}
                                    className="px-6 py-4 bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl font-black text-xs uppercase tracking-widest transition-all active:scale-[0.98] flex items-center gap-2"
                                >
                                    Share
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Summary Card - Dark Glass */}
            <div className="glass-dark p-6 rounded-3xl text-white overflow-hidden relative">
                <div className="absolute top-0 right-0 w-32 h-32 bg-orange-500/10 rounded-full blur-2xl -z-10"></div>
                <div className="grid grid-cols-2 gap-8 relative z-10">
                    <div>
                        <div className="text-[10px] text-slate-400 font-black uppercase tracking-widest mb-1.5">Planned</div>
                        <div className="text-3xl font-black">{plannedCalories} <span className="text-xs font-medium text-slate-500">kcal</span></div>
                    </div>
                    <div className="text-right">
                        <div className="text-[10px] text-slate-400 font-black uppercase tracking-widest mb-1.5">Actual</div>
                        <div className={cn("text-3xl font-black", actualCalories > plannedCalories ? "text-red-400" : "text-emerald-400")}>
                            {actualCalories} <span className="text-xs font-medium text-slate-500">kcal</span>
                        </div>
                    </div>
                </div>
                {/* Visual Bar */}
                <div className="mt-6 h-1.5 bg-slate-800/50 rounded-full overflow-hidden flex">
                    <div
                        className="h-full bg-gradient-to-r from-orange-500 to-rose-500 transition-all duration-1000"
                        style={{ width: `${Math.min(100, (actualCalories / (plannedCalories || 2000)) * 100)}%` }}
                    />
                </div>
                <div className="mt-4 flex items-center justify-between text-[11px] text-slate-400 font-medium">
                    <span>Movement planned today</span>
                    <span>{totalExerciseMinutes} min</span>
                </div>
            </div>

            {/* Meal Sections */}
            <div className="space-y-5">
                <div className="grid grid-cols-4 gap-1 p-1 glass rounded-2xl">
                    {(['breakfast', 'lunch', 'dinner', 'snack'] as const).map(tab => (
                        <button
                            key={tab}
                            onClick={() => setActiveTab(tab)}
                            className={cn(
                                "py-2 rounded-xl text-[10px] font-black uppercase tracking-tighter transition-all capitalize whitespace-nowrap border-2 flex items-center justify-center",
                                activeTab === tab
                                    ? "bg-slate-900 border-slate-900 text-white dark:bg-white dark:border-white dark:text-black shadow-lg shadow-slate-200 dark:shadow-none"
                                    : "bg-white/50 border-slate-100 text-slate-400 dark:bg-slate-900/50 dark:border-slate-800 hover:border-slate-200 dark:hover:border-slate-700"
                            )}
                        >
                            {tab}
                        </button>
                    ))}
                </div>

                <div className="glass p-5 rounded-3xl min-h-[160px]">
                    <div className="flex justify-between items-center mb-5">
                        <div className="flex items-center gap-2">
                            <div className="w-1.5 h-6 bg-orange-500 rounded-full"></div>
                            <h3 className="font-black text-slate-800 dark:text-white capitalize tracking-tight">{activeTab} Entry</h3>
                        </div>
                        <button
                            className="h-9 w-9 p-0 rounded-xl bg-orange-500 text-white flex items-center justify-center shadow-lg shadow-orange-500/20 active:scale-90 transition-transform"
                            onClick={() => {
                                setEditingMeal(null)
                                setIsAddingMode(true)
                            }}
                        >
                            <Plus size={20} />
                        </button>
                    </div>

                    <div className="space-y-3">
                        {entries.length === 0 ? (
                            <div className="text-center py-10 text-slate-400 font-medium text-sm border-2 border-dashed border-slate-100 dark:border-slate-800/50 rounded-2xl">
                                Empty menu
                            </div>
                        ) : (
                            entries.map(entry => (
                                <div
                                    key={entry.id}
                                    className="group relative flex justify-between items-center p-4 bg-white/50 dark:bg-slate-950/50 border border-slate-100 dark:border-slate-800/50 rounded-2xl hover:scale-[1.01] transition-transform"
                                >
                                    <div
                                        onClick={() => {
                                            setEditingMeal(entry)
                                            setIsAddingMode(true)
                                        }}
                                        className="flex-1 cursor-pointer"
                                    >
                                        <span className="font-bold text-slate-700 dark:text-slate-200">{entry.name}</span>
                                        <div className="flex items-center gap-3 mt-1">
                                            <span className="text-[11px] font-black text-slate-400 uppercase tracking-tighter">{entry.calories} Cal</span>
                                            {entry.ingredients && entry.ingredients.length > 0 && (
                                                <span className="text-[9px] font-bold text-indigo-400 uppercase tracking-widest flex items-center gap-1">
                                                    <ShoppingCart size={8} /> {entry.ingredients.length} items
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                    <button
                                        onClick={(e) => {
                                            e.stopPropagation()
                                            removePlanEntry(selectedDate, entry.id)
                                            toast.success("Entry removed")
                                        }}
                                        className="p-2 text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10 rounded-xl transition-all opacity-0 group-hover:opacity-100"
                                        title="Remove entry"
                                    >
                                        <Trash2 size={16} />
                                    </button>
                                </div>
                            ))
                        )}
                    </div>
                </div>
            </div>

            {/* Exercise Planner */}
            <div className="space-y-4">
                <div className="flex items-center justify-between px-1">
                    <div className="flex items-center gap-2">
                        <div className="w-1.5 h-6 bg-emerald-500 rounded-full"></div>
                        <h3 className="font-black text-slate-800 dark:text-white capitalize tracking-tight text-sm">Movement Plan</h3>
                    </div>
                    <button
                        className="h-9 px-3 rounded-xl bg-emerald-500 text-white flex items-center justify-center text-[10px] font-black uppercase tracking-widest shadow-lg shadow-emerald-500/20 active:scale-95 transition-transform"
                        onClick={() => setShowExerciseModal(true)}
                    >
                        <Plus size={16} className="mr-1" />
                        Add Session
                    </button>
                </div>

                <div className="glass p-5 rounded-3xl min-h-[120px]">
                    {(!exerciseLog?.entries || exerciseLog.entries.length === 0) ? (
                        <div className="text-center py-8 text-slate-400 text-sm border-2 border-dashed border-slate-800/40 rounded-2xl">
                            No movement planned yet. Add a short walk, workout, or stretch.
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {exerciseLog.entries.map(entry => (
                                <div
                                    key={entry.id}
                                    className="flex items-center justify-between p-4 bg-slate-900/50 rounded-2xl border border-slate-800/60"
                                >
                                    <div>
                                        <div className="font-bold text-slate-50">
                                            {entry.name}
                                        </div>
                                        <div className="text-[11px] text-slate-400 font-medium mt-1">
                                            {entry.type} • {entry.durationMinutes} min • {entry.intensity}
                                        </div>
                                    </div>
                                    <button
                                        onClick={() => {
                                            removeExerciseEntry(selectedDate, entry.id)
                                            toast.success("Exercise removed")
                                        }}
                                        className="p-2 text-slate-500 hover:text-rose-400 hover:bg-rose-500/10 rounded-xl transition-colors"
                                    >
                                        <Trash2 size={16} />
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            {/* Meal Modal */}
            {isAddingMode && (
                <div className={cn(
                    "fixed inset-0 bg-slate-950/60 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center p-4 animate-in fade-in duration-200 transition-all",
                    !isDesktopView && "left-1/2 -translate-x-1/2 w-full max-w-[430px]"
                )}>
                    <div className="w-full max-w-sm mb-20 sm:mb-0">
                        <AddFoodForm
                            mealType={activeTab}
                            initialValues={editingMeal || undefined}
                            onClose={() => {
                                setIsAddingMode(false)
                                setEditingMeal(null)
                            }}
                            onSubmit={(entry) => {
                                if (editingMeal) {
                                    updatePlanEntry(selectedDate, { ...editingMeal, ...entry })
                                } else {
                                    addPlanEntry(selectedDate, entry)
                                }
                                setIsAddingMode(false)
                                setEditingMeal(null)
                            }}
                        />
                    </div>
                </div>
            )}

            {/* Exercise Modal */}
            {showExerciseModal && (
                <ExerciseModal
                    onClose={() => setShowExerciseModal(false)}
                    onSubmit={async (name, type, minutes, intensity) => {
                        await addExerciseEntry(selectedDate, {
                            name,
                            type,
                            durationMinutes: minutes,
                            intensity
                        })
                        setShowExerciseModal(false)
                        toast.success("Movement added to your plan")
                    }}
                />
            )}

        </div>
    )
}
